# (-*- shell-script -*-)

# path=( "$HOME/bin" "$path[@]" )
# export PATH
# typeset -U path

# Setup Erlang
# export ERL_LIBS=/Users/mjl/work/erlang/mochiweb-read-only/:/Users/mjl/work/erlang/erlyweb-read-only/

# Setup JAVA_HOME
# export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/1.6/Home

# Setup Groovy and Grails
# export GROOVY_HOME=/Users/mjl/work/java/groovy
# export GRAILS_HOME=/Users/mjl/work/java/grails
# path=( "$GROOVY_HOME/bin" "$GRAILS_HOME/bin" "$path[@]" )
# export PATH
# typeset -U path

# Setup Clojure
# export CLOJURE_EXT=$HOME/.clojurelib

if [[ -d /opt/ghc && -d /opt/cabal ]]; then
	export PATH=$PATH:/opt/cabal/head/bin:/opt/ghc/7.10.2/bin
else

fi

