# (-*- shell-script -*-)

# path=( "$HOME/bin" "$path[@]" )
# export PATH
# typeset -U path

# Setup Erlang
# export ERL_LIBS=/Users/mjl/work/erlang/mochiweb-read-only/:/Users/mjl/work/erlang/erlyweb-read-only/

# Setup JAVA_HOME
# export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
# export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
# export JAVA_HOME=/usr/lib/jvm/java-1.9.0-openjdk-amd64

# Setup ANDROID_HOME
if [[ -d $HOME/progs/android ]]; then
	export ANDROID_HOME=$HOME/progs/android
	path=( "$ANDROID_HOME/tools" "$ANDROID_HOME/tools/bin" "$ANDROID_HOME/platform-tools" "$path[@]" )
	export PATH
	typeset -U path
else

fi

# Setup Groovy and Grails
# export GROOVY_HOME=/Users/mjl/work/java/groovy
# export GRAILS_HOME=/Users/mjl/work/java/grails
# path=( "$GROOVY_HOME/bin" "$GRAILS_HOME/bin" "$path[@]" )
# export PATH
# typeset -U path

# Setup Clojure
# export CLOJURE_EXT=$HOME/.clojurelib

if [[ -d /opt/ghc && -d /opt/cabal ]]; then
	export PATH=$PATH:/opt/cabal/1.24/bin:/opt/ghc/7.10.2/bin
else

fi

if [[ -d $HOME/.local/bin ]]; then
	export PATH=$PATH:$HOME/.local/bin
else

fi

if [[ -d /snap/bin ]]; then
	export PATH=$PATH:/snap/bin
else

fi

if [[ -d /var/lib/snapd/desktop ]]; then
	export XDG_DATA_DIRS="$XDG_DATA_DIRS:/var/lib/snapd/desktop/"
else

fi


