# (-*- shell-script -*-)

path=( "$HOME/bin" /opt/local/bin /opt/local/sbin /opt/homebrew/bin /opt/homebrew/opt/libpq/bin /Applications/Xcode.app/Contents/Developer/usr/bin "$path[@]" )
export PATH
typeset -U path

manpath=( /usr/share/man /usr/local/share/man /opt/local/man "$manpath[@]" )
export MANPATH
typeset -U manpath

export LDFLAGS="-L$(brew --prefix readline)/lib -L$(brew --prefix openssl@3)/lib -L$(brew --prefix zlib)/lib" \
export CPPFLAGS="-I$(brew --prefix readline)/include -I$(brew --prefix openssl@3)/include -I$(brew --prefix zlib)/include" \
export PKG_CONFIG_PATH="$(brew --prefix openssl@3)/lib/pkgconfig" \

