# (-*- shell-script -*-)

source ~/dotfiles/zsh/darwin/zshenv

LANG=ko_KR.UTF-8

# Boost headers and libraries
export CPLUS_INCLUDE_PATH=/opt/local/include
export C_INCLUDE_PATH=/opt/local/include
# export DYLD_LIBRARY_PATH=/usr/lib:/opt/local/lib

# for ssh-agent configuration
# zstyle :omz:plugins:ssh-agent agent-forwarding on
# zstyle :omz:plugins:ssh-agent identities ain_rsa young_ige github_rsa

# pnpm
export PNPM_HOME="/Users/ygpark2/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
